apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
  labels:
    app.kubernetes.io/managed-by: eck
---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-stack
  labels:
    app.kubernetes.io/managed-by: eck
