apiVersion: _ES_NAME_.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: _ES_NAME_
  namespace: _NAMESPACE_
spec:
  podDisruptionBudget:
    spec:
      minAvailable: 1
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: _ES_NAME_
  version: _ES_OPERATOR_VERSION_
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  http:
    service:
      spec:
        type: LoadBalancer
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: _ES_NAME_
          namespace: _NAMESPACE_
    logs:
      elasticsearchRefs:
        - name: _ES_NAME_
          namespace: _NAMESPACE_
  secureSettings:
    - secretName: gcs-credentials
  nodeSets:
    - name: master
      count: _ES_NODES_
      volumeClaimTemplates:
        - metadata:
            name: _ES_NAME_-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: _ES_STORAGE_Ti
            storageClassName: premium-rwo
      config:
        node.store.allow_mmap: true
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: _ES_NAME_
              volumeMounts:
                - name: synonyms
                  mountPath: /usr/share/_ES_NAME_/config/synonyms
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms_ES_HEAP_ -Xmx_ES_HEAP_
              resources:
                requests:
                  memory: _ES_MEMORY_Gi
                  cpu: _ES_CPU_
                limits:
                  memory: _ES_MEMORY_LIMIT_Gi
                  cpu: _ES_CPU_LIMIT_
          volumes:
            - name: synonyms
              configMap:
                name: _ES_NAME_-synonyms
