# Point production cluster monitoring to the dedicated monitoring cluster
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ${ES_CLUSTER_NAME}
  namespace: elastic-stack
spec:
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: ${MONITORING_CLUSTER_NAME}
    logs:
      elasticsearchRefs:
        - name: ${MONITORING_CLUSTER_NAME}
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ${ES_CLUSTER_NAME}
  namespace: elastic-stack
spec:
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: ${MONITORING_CLUSTER_NAME}
    logs:
      elasticsearchRefs:
        - name: ${MONITORING_CLUSTER_NAME}
